DROP VIEW CLIENTES_POR_PAGAR;
CREATE VIEW CLIENTES_POR_PAGAR AS
SELECT DISTINCT DC.ID_CLIENTE, C.NOME_CLIENTE, CT.NR_TELEFONE, CT.EMAIL, TD.TOTAL
FROM DOC_CABECALHO DC
INNER JOIN TOTAL_DOC TD ON (DC.NR_DOCUMENTO = TD.NR_DOCUMENTO AND DC.ID_CLIENTE = TD.NR_CLIENTE)
INNER JOIN CLIENTE C ON (DC.ID_CLIENTE = C.ID_CLIENTE AND TD.NR_CLIENTE = C.ID_CLIENTE)
INNER JOIN CONTATOS CT ON (C.ID_CLIENTE = CT.ID_CLIENTE)
WHERE (
	DC.TIPO_DOC = 2
	AND TD.TIPO_DOC = 2
	AND DC.NR_DOCUMENTO NOT IN (SELECT NR_FATURA FROM Recibo)
	)
ORDER BY ID_CLIENTE;

SELECT ID_CLIENTE, NOME_CLIENTE, NR_TELEFONE, EMAIL, ROUND(TOTAL, 2) TOTAL FROM CLIENTES_POR_PAGAR;