DROP VIEW TOTAL_PRODUTO;
CREATE VIEW TOTAL_PRODUTO AS
	SELECT P.ID_PRODUTO, DESCRICAO,
	(SELECT P1.PRECO * (1+P1.LUCRO) * (SELECT 1 + I.VALOR FROM IVA I WHERE
		ID_IVA = P1.ID_IVA) FROM PRODUTO P1 WHERE (P.ID_PRODUTO = P1.ID_PRODUTO)) VALOR
	FROM PRODUTO P;

SELECT ID_PRODUTO, DESCRICAO, ROUND(VALOR, 2) FROM TOTAL_PRODUTO;