DROP VIEW TOTAL_DOC;
CREATE VIEW TOTAL_DOC AS
	SELECT DD.NR_DOCUMENTO, DD.TIPO_DOC, DD.NR_CLIENTE, SUM(TP.VALOR * DD.PESO) TOTAL
	FROM DOC_DETALHE DD, TOTAL_PRODUTO TP
	WHERE (DD.ID_PRODUTO = TP.ID_PRODUTO)
	GROUP BY DD.NR_DOCUMENTO, DD.TIPO_DOC, DD.NR_CLIENTE
	ORDER BY DD.NR_DOCUMENTO;

SELECT NR_DOCUMENTO, TIPO_DOC, NR_CLIENTE, ROUND(TOTAL, 2) TOTAL FROM TOTAL_DOC;